### ISSUE TITLE
How to include in f-droid?

### ISSUE THREAD

**Issue by dalb8** [rjmarsan/Pixelesque#3]
F-droid is a repository for Foss (free and open source software) on Android . This app has been proposed for inclusion, but I am not sure if you wish it to be included with the current name or the artwork. It would be a trivial matter to substitute these, but it would be confusing for users.

**Comment by dalb8** [comment]
The same goes for Plasma Sound.

**Comment by rjmarsan** [comment]
Sorry, I didn't realize that'd be a big issue.  I changed the artwork and name to be creative commons noncommercial-sharealike, which should fit in perfectly with F-Droid.  Same with plasma sound.

**Comment by dalb8** [comment]
Thank you. It may not have been an issue but I wasn't sure.
